interface IVerbs {
  infinitive: string;
  pastSimple: string;
  pastParticipe: string;
}
export const verbsList: IVerbs[] = [
  { infinitive: "be", pastSimple: "was/were", pastParticipe: "been" },
  { infinitive: "become", pastSimple: "became", pastParticipe: "become" },
  { infinitive: "begin", pastSimple: "began", pastParticipe: "begun" },
  { infinitive: "break", pastSimple: "broke", pastParticipe: "broken" },
  { infinitive: "bring", pastSimple: "brought", pastParticipe: "brought" },
  { infinitive: "buy", pastSimple: "bought", pastParticipe: "bought" },
  { infinitive: "choose", pastSimple: "chose", pastParticipe: "chosen" },
  { infinitive: "come", pastSimple: "came", pastParticipe: "come" },
  { infinitive: "do", pastSimple: "did", pastParticipe: "done" },
  { infinitive: "drink", pastSimple: "drank", pastParticipe: "drunk" },
  { infinitive: "drive", pastSimple: "drove", pastParticipe: "driven" },
  { infinitive: "eat", pastSimple: "ate", pastParticipe: "eaten" },
  { infinitive: "fall", pastSimple: "fell", pastParticipe: "fallen" },
  { infinitive: "feel", pastSimple: "felt", pastParticipe: "felt" },
  { infinitive: "find", pastSimple: "found", pastParticipe: "found" },
  { infinitive: "fly", pastSimple: "flew", pastParticipe: "flown" },
  { infinitive: "forget", pastSimple: "forgot", pastParticipe: "forgotten" },
  { infinitive: "get", pastSimple: "got", pastParticipe: "gotten" },
  { infinitive: "give", pastSimple: "gave", pastParticipe: "given" },
  { infinitive: "go", pastSimple: "went", pastParticipe: "gone" },
  { infinitive: "have", pastSimple: "had", pastParticipe: "had" },
  { infinitive: "hear", pastSimple: "heard", pastParticipe: "heard" },
  { infinitive: "keep", pastSimple: "kept", pastParticipe: "kept" },
  { infinitive: "know", pastSimple: "knew", pastParticipe: "known" },
  { infinitive: "leave", pastSimple: "left", pastParticipe: "left" },
  { infinitive: "make", pastSimple: "made", pastParticipe: "made" },
  { infinitive: "meet", pastSimple: "met", pastParticipe: "met" },
  { infinitive: "pay", pastSimple: "paid", pastParticipe: "paid" },
  { infinitive: "read", pastSimple: "read", pastParticipe: "read" },
  { infinitive: "run", pastSimple: "ran", pastParticipe: "run" },
  { infinitive: "see", pastSimple: "saw", pastParticipe: "seen" },
  { infinitive: "send", pastSimple: "sent", pastParticipe: "sent" },
  { infinitive: "sing", pastSimple: "sang", pastParticipe: "sung" },
  { infinitive: "sit", pastSimple: "sat", pastParticipe: "sat" },
  { infinitive: "speak", pastSimple: "spoke", pastParticipe: "spoken" },
  { infinitive: "swim", pastSimple: "swam", pastParticipe: "swum" },
  { infinitive: "take", pastSimple: "took", pastParticipe: "taken" },
  { infinitive: "teach", pastSimple: "taught", pastParticipe: "taught" },
  { infinitive: "tell", pastSimple: "told", pastParticipe: "told" },
  { infinitive: "think", pastSimple: "thought", pastParticipe: "thought" },
  { infinitive: "write", pastSimple: "wrote", pastParticipe: "written" },
];
