import { IVerbs } from "../interface/Verbs";

export const verbsList: IVerbs[] = [
  { infinitive: "arise", pastSimple: "arose", pastParticiple: "arisen" },
  { infinitive: "awake", pastSimple: "awoke", pastParticiple: "awoken" },
  { infinitive: "be", pastSimple: "was/were", pastParticiple: "been" },
  { infinitive: "bear", pastSimple: "bore", pastParticiple: "borne" },
  { infinitive: "beat", pastSimple: "beat", pastParticiple: "beaten" },
  { infinitive: "become", pastSimple: "became", pastParticiple: "become" },
  { infinitive: "begin", pastSimple: "began", pastParticiple: "begun" },
  { infinitive: "bend", pastSimple: "bent", pastParticiple: "bent" },
  { infinitive: "bet", pastSimple: "bet", pastParticiple: "bet" },
  { infinitive: "bid", pastSimple: "bid", pastParticiple: "bid" },
  { infinitive: "bind", pastSimple: "bound", pastParticiple: "bound" },
  { infinitive: "bite", pastSimple: "bit", pastParticiple: "bitten" },
  { infinitive: "bleed", pastSimple: "bled", pastParticiple: "bled" },
  { infinitive: "blow", pastSimple: "blew", pastParticiple: "blown" },
  { infinitive: "break", pastSimple: "broke", pastParticiple: "broken" },
  { infinitive: "breed", pastSimple: "bred", pastParticiple: "bred" },
  { infinitive: "bring", pastSimple: "brought", pastParticiple: "brought" },
  {
    infinitive: "broadcast",
    pastSimple: "broadcast",
    pastParticiple: "broadcast",
  },
  { infinitive: "build", pastSimple: "built", pastParticiple: "built" },
  {
    infinitive: "burn",
    pastSimple: "burned/burnt",
    pastParticiple: "burned/burnt",
  },
  { infinitive: "burst", pastSimple: "burst", pastParticiple: "burst" },
  { infinitive: "buy", pastSimple: "bought", pastParticiple: "bought" },
  { infinitive: "cast", pastSimple: "cast", pastParticiple: "cast" },
  { infinitive: "catch", pastSimple: "caught", pastParticiple: "caught" },
  { infinitive: "choose", pastSimple: "chose", pastParticiple: "chosen" },
  { infinitive: "cling", pastSimple: "clung", pastParticiple: "clung" },
  { infinitive: "come", pastSimple: "came", pastParticiple: "come" },
  { infinitive: "cost", pastSimple: "cost", pastParticiple: "cost" },
  { infinitive: "creep", pastSimple: "crept", pastParticiple: "crept" },
  { infinitive: "cut", pastSimple: "cut", pastParticiple: "cut" },
  { infinitive: "deal", pastSimple: "dealt", pastParticiple: "dealt" },
  { infinitive: "dig", pastSimple: "dug", pastParticiple: "dug" },
  { infinitive: "do", pastSimple: "did", pastParticiple: "done" },
  { infinitive: "draw", pastSimple: "drew", pastParticiple: "drawn" },
  {
    infinitive: "dream",
    pastSimple: "dreamed/dreamt",
    pastParticiple: "dreamed/dreamt",
  },
  { infinitive: "drink", pastSimple: "drank", pastParticiple: "drunk" },
  { infinitive: "drive", pastSimple: "drove", pastParticiple: "driven" },
  { infinitive: "eat", pastSimple: "ate", pastParticiple: "eaten" },
  { infinitive: "fall", pastSimple: "fell", pastParticiple: "fallen" },
  { infinitive: "feed", pastSimple: "fed", pastParticiple: "fed" },
  { infinitive: "feel", pastSimple: "felt", pastParticiple: "felt" },
  { infinitive: "fight", pastSimple: "fought", pastParticiple: "fought" },
  { infinitive: "find", pastSimple: "found", pastParticiple: "found" },
  { infinitive: "flee", pastSimple: "fled", pastParticiple: "fled" },
  { infinitive: "fly", pastSimple: "flew", pastParticiple: "flown" },
  { infinitive: "forbid", pastSimple: "forbade", pastParticiple: "forbidden" },
  { infinitive: "forget", pastSimple: "forgot", pastParticiple: "forgotten" },
  { infinitive: "forgive", pastSimple: "forgave", pastParticiple: "forgiven" },
  { infinitive: "freeze", pastSimple: "froze", pastParticiple: "frozen" },
  { infinitive: "get", pastSimple: "got", pastParticiple: "got/gotten" },
  { infinitive: "give", pastSimple: "gave", pastParticiple: "given" },
  { infinitive: "go", pastSimple: "went", pastParticiple: "gone" },
  { infinitive: "grow", pastSimple: "grew", pastParticiple: "grown" },
  { infinitive: "hang", pastSimple: "hung", pastParticiple: "hung" },
  { infinitive: "have", pastSimple: "had", pastParticiple: "had" },
  { infinitive: "hear", pastSimple: "heard", pastParticiple: "heard" },
  { infinitive: "hide", pastSimple: "hid", pastParticiple: "hidden" },
  { infinitive: "hit", pastSimple: "hit", pastParticiple: "hit" },
  { infinitive: "hold", pastSimple: "held", pastParticiple: "held" },
  { infinitive: "hurt", pastSimple: "hurt", pastParticiple: "hurt" },
  { infinitive: "keep", pastSimple: "kept", pastParticiple: "kept" },
  { infinitive: "kneel", pastSimple: "knelt", pastParticiple: "knelt" },
  { infinitive: "know", pastSimple: "knew", pastParticiple: "known" },
  { infinitive: "lay", pastSimple: "laid", pastParticiple: "laid" },
  { infinitive: "lead", pastSimple: "led", pastParticiple: "led" },
  {
    infinitive: "lean",
    pastSimple: "leaned/leant",
    pastParticiple: "leaned/leant",
  },
  {
    infinitive: "leap",
    pastSimple: "leaped/leapt",
    pastParticiple: "leaped/leapt",
  },
  {
    infinitive: "learn",
    pastSimple: "learned/learnt",
    pastParticiple: "learned/learnt",
  },
  { infinitive: "leave", pastSimple: "left", pastParticiple: "left" },
  { infinitive: "lend", pastSimple: "lent", pastParticiple: "lent" },
  { infinitive: "let", pastSimple: "let", pastParticiple: "let" },
  { infinitive: "lie", pastSimple: "lay", pastParticiple: "lain" },
  { infinitive: "light", pastSimple: "lit", pastParticiple: "lit" },
  { infinitive: "lose", pastSimple: "lost", pastParticiple: "lost" },
  { infinitive: "make", pastSimple: "made", pastParticiple: "made" },
  { infinitive: "mean", pastSimple: "meant", pastParticiple: "meant" },
  { infinitive: "meet", pastSimple: "met", pastParticiple: "met" },
  { infinitive: "mow", pastSimple: "mowed", pastParticiple: "mowed/mown" },
  { infinitive: "pay", pastSimple: "paid", pastParticiple: "paid" },
  {
    infinitive: "plead",
    pastSimple: "pleaded/pled",
    pastParticiple: "pleaded/pled",
  },
  {
    infinitive: "prove",
    pastSimple: "proved",
    pastParticiple: "proved/proven",
  },
];
console.log(verbsList.length);
